server.port: 8080

spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8000
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"