server.port: 8080

spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${user-service.url}
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

user-service:
  url: http://localhost:8000

management:
  endpoints:
    web:
      exposure:
        include: "*"