server.port: 8090

spring:
  application.name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfiguration:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
#      httpclient:
#        wiretap: true
#      httpserver:
#        wiretap: true
      routes:
        - id: user-service
          uri: ${user-service.url}
          predicates:
            - Path=/users/**
            - Method=GET,PUT
          filters:
            - StripPrefix=1
            - AuthFilter

user-service:
  url: http://localhost:8000

management:
  endpoints:
    web:
      exposure:
        include: "*"